lagnuage: go
go:
- 1.13.x
git:
  depth: 1
go_import_path:
- github.com/kolide/osquery-go
- github.com/StackExchange/wmi
- github.com/go-ole/go-ole
- github.com/shirou/gopsutil
- golang.org/x/sys
script:
- GOOS=windows GOARCH=amd64 go build -o osquery_malware_removal.exe osquery-malware-removal.go
- GOOS=darwin GOARCH=amd64 go build -o osquery_malware_removal.macho osquery-malware-removal.go
- GOOS=linux GOARCH=amd64 go build -o osquery_malware_removal.elf osquery-malware-removal.go
notifications:
  email: true
deploy:
  provider: releases
  api_key:
    secure: tLuD3yjTrWsXCXm+1YwOfyqIVuK4XkzroTVABgAk/ya/b9VqlgLITI3rEljTKzkgSQNPxnukEq07QCiPe4pURioDPLg2o8mEuywcGqZgzqxShVMiUImuW9zHRmvM/mV8l6wyYAFqizz+dKikgTvwgOsJpg8cAjoi0A4jc9ci8ePBL0agShQ7EmeZwMAzFpX7rVHr6TOxX0goWb78doOJymrFOUeUs/l3GH4exJqW1ErLySb9xg5Z0fBGMqOmSCnifLUnqTyEvxvOoHXQTOmAV48wC2LFxec2wYR7xQIXHt5r/wwOZLAAnXFOQSse16F3nIeAhfm7qLNZjK0kYOUgqnnrQCmC7FF0FKjjxnTvlQjmtspIjQ+JzW61yBwg12i8nvHp3YFOm/f611irFkpvEzo+2QfnRfarrjHyzzsJ9tIOFZbuwXuvHEBIUPY14dIulX50OTJCNw38uZVmSvsFKhjX8cPYiGBnjB5Aey7pIa0ZJ8TnuDDtmSbUCjzPsOrVQPh4QcQXyZCGh5rWx2E3O2zud9oE1cM+P1Y2JQ57+s75OCqi5/g08X6vJtEUAGUZ5L9joYLoIaF0ZbvRsKdBTX4qMxpZuewCkA9c8ZreI+7S2O3qogGZ7EMgTHy16cXdyUY56hCzrhMEZ+rzvPdazjRDcjXOIfv31+VC6L59cfw=
  file: 
    - osquery_malware_removal.exe
    - osquery_malware_removal.macho
    - osquery_malware_removal.elf
  on:
    repo: CptOfEvilMinions/osquery-malware-removal
