lagnuage: go

# Specify go version
go:
  - 1.13.x

# Only clone the most recent commit.
git:
  depth: 1

# Grab GO modules
go_import_path:
  - github.com/kolide/osquery-go

# Commands to build binaries
script:
  - GOOS=windows GOARCH=amd64 go build -o osquery_malware_removal.exe osquery-malware-removal.go
  - GOOS=darwin GOARCH=amd64 go build -o osquery_malware_removal.macho osquery-malware-removal.go
  - GOOS=linux GOARCH=amd64 go build -o osquery_malware_removal.elf osquery-malware-removal.go

# Don't email me the results of the test runs.
notifications:
  email: true