lagnuage: go
go:
- 1.13.x
git:
  depth: 1
go_import_path:
- github.com/StackExchange/wmi v0.0.0-20190523213315-cbe66965904d
- github.com/go-ole/go-ole v1.2.4
- github.com/kolide/osquery-go v0.0.0-20190904034940-a74aa860032d
- github.com/shirou/gopsutil v2.20.1+incompatible
- golang.org/x/sys v0.0.0-20200219091948-cb0a6d8edb6c
script:
- GOOS=windows GOARCH=amd64 go build -o osquery_malware_removal.exe osquery-malware-removal.go
- GOOS=darwin GOARCH=amd64 go build -o osquery_malware_removal.macho osquery-malware-removal.go
- GOOS=linux GOARCH=amd64 go build -o osquery_malware_removal.elf osquery-malware-removal.go
notifications:
  email: true
deploy:
  provider: releases
  api_key:
    secure: UL2ROUGdeGFpnlRAAQHHTVYhJxOMkIlkfImyOpcOd37wp4D0+sOgbDyQOyzyurkjUFj1R0ogjHv0/W4HSRr58+200nrSdvBhANvYZtZe+I2nuk4NNcmnNvQK2WpjW7mGvjpD+ndV63iIyjTNgqGIbeTJx3EwuCTTaFkfAF6K3A71GXt5fiH3/1R7w7nvrXJarDMn6Bxh3Y5L4elOa/rpPPgdU/IvJFKCvLgnWBY8G82xm5ZL8MLEXFpJmPMDQo8uwqeLNaIGOufeSdB75IZxiF0ipvkbee+fvYpffAV8R3dfYPqjhOhmf6acvqa61Hdej8IIyN2A2f9HDT0WCl9kzKgR0kj6c5N8jwJTZb+UFy7L7SAxA6hlaEpqFQVLE73vnBd9KqYvI9U/UelC2Dxn4Tagvp/qtyR3TEICBTURTXY+TONttpYlatWmMTYinM6vh8WRAmuMUpxMhRritQAb0ORT1VLPK0WCfvAVbjam3ICYmYPAfezKNh5TJmSYYbxKvR5goC+9jYEEsPNL7nOuqqYtkuioLgiY7znAYvZhjFod+U+Yn1p+57qiSdtgUdZwDWyg5w30ddZTQ68BzhWS2k08DWNMfHpwrsvztjRsni2cdByh3mYCcmESXU+sDU9z92bOliGxPHzPi0PCrPYzGCBhQX0L3NhCVv9J/o1r1Qw=
  file: osquery_malware_removal.exe
  on:
    repo: CptOfEvilMinions/osquery-malware-removal
  edge: true
